name: Build HapticVision
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -project HapticVision.xcodeproj -scheme HapticVision -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build
